### PR TITLE
Added option to open dead threads

### PR DESCRIPTION
**Pull request by puckzxz**

### CODE REVIEW

**Comment by ccd0** [comment]
Can you explain the use case for this?

**Comment by puckzxz** [comment]
At times I'll have over 30 dead threads I want to view and it can get tedious to middle click every thread in the thread watcher window. I tried to find a way to only open dead threads initially but sadly the only 2 options available were to open **all** threads, or prune dead threads. I've been using the feature for a while now and it's been working great for my needs so I opened a PR in case anyone else could benefit from it.

**Comment by ccd0** [comment]
Why only dead threads specifically, though?

**Comment by puckzxz** [comment]
As I said before, I watch a lot of threads and I want to check them after they die. It's much easier to open all the dead threads in one click than to individually middle click each one.

Here is a small example,


msedge_2021-05-08_11-50-48
msedge_2021-05-08_11-47-56

And then I go through each thread to see if I missed anything.

**Comment by puckzxz** [comment]
Maybe it would be suitable now to change buttons from

- Open all threads
- Open dead threads

to

- Open active threads
- Open dead threads

since we have the ability now to open only dead threads?

**Comment by ccd0** [comment]
Yeah, but the question was, why do you only want to check the dead ones?

**Comment by puckzxz** [comment]
I think I explained it fairly well here https://github.com/ccd0/4chan-x/pull/2914#issuecomment-835410853

**Comment by puckzxz** [comment]
Sorry, I prune all the dead threads after I've read them to keep the thread watcher tidy.

**Comment by ccd0** [comment]
Thanks, that makes sense now.

**Comment by ccd0** [comment]
> Maybe it would be suitable now to change buttons from
> 
>     * Open all threads
> 
>     * Open dead threads
> 
> 
> to
> 
>     * Open active threads
> 
>     * Open dead threads
> 
> 
> since we have the ability now to open only dead threads?

Maybe if there's someone who wants to open only live threads.

Because of #2945 the current menu is:

* Open all threads
* Open unread threads
* Open dead threads

Thanks for the PR; it should go out for testing in the next beta version.

**Pull request merged**
