### PR TITLE
Add whatanime.ga to sauces, see #943

### LINKED ISSUE #943: Add whatanime.ga to Sauce list
<s>`https://whatanime.ga/?url=%IMG`</s>
`https://whatanime.ga/?auto&url=%IMG`

Looks very useful. Might even be worth adding enabled-by-default.

### PR DESCRIPTION
**Pull request by r3c0d3x**
Adding whatanime.ga to the sauce list to close #943.

You suggested making it a default; should I?

### CODE REVIEW

**Comment by ccd0** [comment]
> You suggested making it a default; should I?

I'm still thinking about it. What are your thoughts?

Small notes, I don't like closing issues from commit messages (I usually wait until stuff is in stable to close the issue, and last I checked it interfered with me re-opening issues that were closed that way), and we'd probably want to also append it to people's existing lists as in https://github.com/ccd0/4chan-x/blob/1.11.34.7/src/General/Settings.coffee#L370.

**Comment by r3c0d3x** [comment]
> What are your thoughts?

I personally don't really have a preference. (I don't really watch anime so it personally doesn't matter to me, but...)

>  we'd probably want to also append it to people's existing lists

Good idea, just pushed another commit for it.

**Comment by ccd0** [comment]
It doesn't belong in the 1.11.32.0 changes, though. It would be going in in 1.11.35.0.

You should test that the code is working by editing the Sauce settings (otherwise it will just use the new default), changing the version number in
https://github.com/ccd0/4chan-x/blob/master/version.json
recompiling, installing (this should happen automatically when you run `make` if you put `{"testbuilds/4chan-X-beta.user.js": ["YOURPROFILEDIRECTORY/gm_scripts/4chan_X_beta/4chan-X-beta.user.js"]}` in install.json), reloading the page, and checking whether the new item gets appended.

Also the "Closes ccd0/4chan-x#943" in the commit message will also close the issue and should be removed.

**Comment by ccd0** [comment]
I added whatanime.ga in 98a0fff3d220ce32068bc954e0a5b5f8fb715905.

**Pull request closed without merging**
