### PR TITLE
Rotate image/video in gallery view mode

### PR DESCRIPTION
**Pull request by droM4X**
I made this feature request, what I mentioned in #2362 

Shift+Left or Right will rotate the current image or video in gallery view mode and keeps its aspect ratio.

I hope its ok, this was my first coffeescript attempt :)

### CODE REVIEW

**Comment by ccd0** [comment]
Thanks, I'll test it out.
Just from looking at the code, the duplicate stuff should be condensed into one function that takes +90 or -90 as an argument.

**Comment by ccd0** [comment]
Also I assume you didn't mean to change package-lock.json.

**Comment by ccd0** [comment]
This line seems to be in error (one argument to Math.min, no parentheses around `doc.clientHeight - 25`)

>`style.width = Math.min(doc.clientHeight - 25 / (width / height)) + 'px'`

Also this gets it wrong if `current.dataRotate` is -90:

>`if (current.dataRotate == 90 || current.dataRotate == 270)`

I think `Gallery.setHeight` (used for "Stretch to Fit") will also need an update to account for rotation.

**Comment by ccd0** [comment]
> `style.width = Math.min(doc.clientHeight - 25 / (width / height)) + 'px'`

Okay, I think what you want here is just

`style.maxWidth = (doc.clientHeight - 25) + 'px'`

And it should only be applied if "Fit Height" is enabled.

I say `maxWidth` here because we need to override the `maxWidth` from the CSS, which otherwise becomes a bogus constraint on the height.

There also needs to be something done in the height > width case.

**Comment by ccd0** [comment]
Alright, I think I fixed everything. Thanks!

**Comment by droM4X** [comment]
Nice, thanks for the fixes.

**Pull request merged**
