### PR TITLE
Update 4chanJS favicons to reflect the native extension

### PR DESCRIPTION
**Pull request by desaku**

### CODE REVIEW

**Comment by desaku** [comment]
Fuck, I closed the PR instead of submitting it

**Comment by ccd0** [comment]
Thanks! Should be in beta (v1.13.1.6) now.

**Comment by ccd0** [comment]
By the way, since presumably you'll be among the ones using this icon set, do you think I should change the red exclamation mark on the dead+reply-to-you icon from red to some other color such as green? I'm worried it doesn't stand out very well as is.

exclamation-green

In the native extension, there's no exclamation points at all in dead threads, which is not something we want to emulate.

**Comment by desaku** [comment]
I like it, red-on-red is hard to make out. Would some shade of yellow be more appropriate for the exclamation mark? Green feels like there's still some action the user can take.

**Comment by ccd0** [comment]
My concern with yellow is that it looks a bit too close to white.
exclamation-yellow

**Comment by desaku** [comment]
Maybe a darker shade of yellow? I don't mind either way, it's pretty hard to make any color other than green stand out well.

darker

**Pull request merged**
